'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Loader2 } from 'lucide-react'

type Phase = 'intro' | 'focus' | 'questions' | 'email' | 'generating' | 'result'

const FOCUS_OPTIONS = [
  {
    id: 'pattern',
    label: 'A relationship pattern I keep repeating',
    sub: 'Something that plays out with different people, but always the same way.',
  },
  {
    id: 'stuck',
    label: 'A place where I feel stuck',
    sub: 'I know something needs to change. I just cannot get there.',
  },
  {
    id: 'unexplained',
    label: 'Something I cannot explain about myself',
    sub: 'A part of me I have never been able to account for to anyone.',
  },
  {
    id: 'wound',
    label: 'A wound that keeps getting activated',
    sub: 'Something I thought I had dealt with. I have not.',
  },
]

const QUESTIONS = [
  {
    prompt: 'Tell me about it in your own words.',
    sub: 'Not the polished version. The one that still has texture in it.',
  },
  {
    prompt: 'When you sit with this, what do you feel?',
    sub: 'Not the thought about the feeling. The feeling itself, and where it lives.',
  },
  {
    prompt: 'Is there something you already know about why this keeps showing up, but have not been able to fully believe yet?',
    sub: 'Take your time with this one.',
  },
  {
    prompt: 'Who else is in this?',
    sub: 'Even if they are not obviously present, whose face or voice comes to mind?',
  },
  {
    prompt: 'If you could say one true thing about this that you have not let yourself say out loud yet, what would it be?',
    sub: 'You do not have to hold back here.',
  },
]


export default function MiniMapPage() {
  const [phase, setPhase] = useState<Phase>('intro')
  const [focusArea, setFocusArea] = useState('')
  const [answers, setAnswers] = useState<string[]>(Array(QUESTIONS.length).fill(''))
  const [questionIndex, setQuestionIndex] = useState(0)
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [error, setError] = useState('')

  function updateAnswer(value: string) {
    const next = [...answers]
    next[questionIndex] = value
    setAnswers(next)
  }

  function nextQuestion() {
    if (questionIndex < QUESTIONS.length - 1) {
      setQuestionIndex(questionIndex + 1)
    } else {
      setPhase('email')
    }
  }

  async function handleSubmit() {
    setError('')
    setPhase('generating')
    try {
      const res = await fetch('/api/mini-map', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, email, focusArea, answers }),
      })
      const data = await res.json()
      if (res.status === 409) {
        setError('A map has already been sent to this email address. Check your inbox.')
        setPhase('email')
        return
      }
      if (res.status === 429) {
        setError('You have already requested a map fragment today. Check your inbox or try again tomorrow.')
        setPhase('email')
        return
      }
      if (res.status === 503) {
        setError('The map fragment tool is temporarily unavailable. Please try again tomorrow.')
        setPhase('email')
        return
      }
      if (!res.ok) throw new Error(data.error || 'Unknown error')
      setPhase('result')
    } catch {
      setError('Something went wrong. Please try again.')
      setPhase('email')
    }
  }

  // ── INTRO ──────────────────────────────────────────────────────────────────
  if (phase === 'intro') {
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center px-6 text-center">
        <p className="text-[10px] font-mono tracking-[0.35em] text-teal-400 uppercase mb-8">ReLoHu</p>
        <h1 className="text-3xl md:text-4xl font-light text-white mb-5 max-w-lg leading-snug">
          Your First Map Fragment
        </h1>
        <p className="text-slate-400 text-lg mb-3 max-w-md leading-relaxed">
          Five questions. About five minutes. A glimpse of what it feels like to be genuinely seen.
        </p>
        <p className="text-slate-500 text-sm mb-12 max-w-md leading-relaxed">
          At the end, you will receive a short written portrait of what you shared, generated by the same AI methodology behind every full Terrain Map.
        </p>
        <button
          onClick={() => setPhase('focus')}
          className="bg-teal-600 hover:bg-teal-500 text-white px-10 py-4 rounded-full font-medium text-lg transition-colors"
        >
          Begin
        </button>
        <Link
          href="/"
          className="mt-8 text-slate-600 hover:text-slate-400 text-sm transition-colors"
        >
          Back to ReLoHu
        </Link>
      </div>
    )
  }

  // ── FOCUS PICKER ───────────────────────────────────────────────────────────
  if (phase === 'focus') {
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center px-6 py-16">
        <div className="max-w-xl w-full">
          <p className="text-[10px] font-mono tracking-[0.35em] text-teal-400 uppercase mb-8">
            Step 1 of 6
          </p>
          <h2 className="text-2xl font-light text-white mb-2">What do you want to focus on?</h2>
          <p className="text-slate-400 mb-10 leading-relaxed">
            Choose the area that feels most alive right now.
          </p>
          <div className="space-y-3">
            {FOCUS_OPTIONS.map((opt) => (
              <button
                key={opt.id}
                onClick={() => {
                  setFocusArea(opt.id)
                  setQuestionIndex(0)
                  setPhase('questions')
                }}
                className="w-full text-left bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-teal-600 rounded-xl p-5 transition-all group"
              >
                <p className="text-white font-medium mb-1 group-hover:text-teal-300 transition-colors">
                  {opt.label}
                </p>
                <p className="text-slate-500 text-sm">{opt.sub}</p>
              </button>
            ))}
          </div>
          <Link
            href="/"
            className="mt-10 block text-center text-slate-600 hover:text-slate-400 text-sm transition-colors"
          >
            Back
          </Link>
        </div>
      </div>
    )
  }

  // ── QUESTIONS ──────────────────────────────────────────────────────────────
  if (phase === 'questions') {
    const q = QUESTIONS[questionIndex]
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center px-6 py-16">
        <div className="max-w-xl w-full">
          {/* Progress bar */}
          <div className="flex gap-1.5 mb-10">
            {QUESTIONS.map((_, i) => (
              <div
                key={i}
                className={`h-0.5 flex-1 rounded-full transition-colors duration-300 ${
                  i <= questionIndex ? 'bg-teal-500' : 'bg-slate-700'
                }`}
              />
            ))}
          </div>

          <p className="text-[10px] font-mono tracking-[0.35em] text-teal-400 uppercase mb-8">
            Question {questionIndex + 2} of 6
          </p>
          <h2 className="text-2xl font-light text-white mb-2 leading-snug">{q.prompt}</h2>
          {q.sub && <p className="text-slate-400 mb-8 leading-relaxed">{q.sub}</p>}

          <textarea
            value={answers[questionIndex]}
            onChange={(e) => updateAnswer(e.target.value)}
            placeholder="Write here..."
            rows={6}
            autoFocus
            className="w-full bg-slate-800 border border-slate-700 focus:border-teal-500 rounded-xl p-5 text-white placeholder-slate-600 resize-none outline-none transition-colors text-base leading-relaxed"
          />

          <div className="flex justify-between items-center mt-6">
            <button
              onClick={() => {
                if (questionIndex === 0) setPhase('focus')
                else setQuestionIndex(questionIndex - 1)
              }}
              className="text-slate-500 hover:text-slate-300 text-sm transition-colors"
            >
              Back
            </button>
            <button
              onClick={nextQuestion}
              disabled={!answers[questionIndex].trim()}
              className="bg-teal-600 hover:bg-teal-500 disabled:opacity-30 disabled:cursor-not-allowed text-white px-8 py-3 rounded-full font-medium transition-all flex items-center gap-2"
            >
              {questionIndex < QUESTIONS.length - 1 ? 'Continue' : 'Last step'}
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    )
  }

  // ── EMAIL CAPTURE ──────────────────────────────────────────────────────────
  if (phase === 'email') {
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center px-6 py-16">
        <div className="max-w-md w-full">
          <p className="text-[10px] font-mono tracking-[0.35em] text-teal-400 uppercase mb-8">
            Step 6 of 6
          </p>
          <h2 className="text-2xl font-light text-white mb-2">Where should we send your map?</h2>
          <p className="text-slate-400 mb-10 leading-relaxed">
            Your map fragment will appear on screen and be sent to your email. No sequences. No pitches. Just the map.
          </p>

          <div className="space-y-4">
            <div>
              <label className="text-slate-400 text-sm mb-2 block">Your name</label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="First name is fine"
                className="w-full bg-slate-800 border border-slate-700 focus:border-teal-500 rounded-xl px-5 py-4 text-white placeholder-slate-600 outline-none transition-colors"
              />
            </div>
            <div>
              <label className="text-slate-400 text-sm mb-2 block">Your email</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="you@example.com"
                className="w-full bg-slate-800 border border-slate-700 focus:border-teal-500 rounded-xl px-5 py-4 text-white placeholder-slate-600 outline-none transition-colors"
              />
            </div>
          </div>

          {error && <p className="text-red-400 text-sm mt-4">{error}</p>}

          <button
            onClick={handleSubmit}
            disabled={!name.trim() || !email.trim()}
            className="w-full mt-8 bg-teal-600 hover:bg-teal-500 disabled:opacity-30 disabled:cursor-not-allowed text-white py-4 rounded-full font-medium text-lg transition-all"
          >
            Generate my map
          </button>

          <p className="text-slate-600 text-xs text-center mt-4">
            Your responses are kept confidential.
          </p>

          <button
            onClick={() => {
              setQuestionIndex(QUESTIONS.length - 1)
              setPhase('questions')
            }}
            className="mt-6 block w-full text-center text-slate-600 hover:text-slate-400 text-sm transition-colors"
          >
            Back
          </button>
        </div>
      </div>
    )
  }

  // ── GENERATING ─────────────────────────────────────────────────────────────
  if (phase === 'generating') {
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center px-6 text-center">
        <Loader2 className="w-8 h-8 text-teal-400 animate-spin mb-6" />
        <p className="text-white text-lg font-light mb-2">Reading what you shared.</p>
        <p className="text-slate-500 text-sm">This takes about 20 seconds.</p>
      </div>
    )
  }

  // ── RESULT ─────────────────────────────────────────────────────────────────
  if (phase === 'result') {
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center px-6 text-center">
        <div className="max-w-md w-full">
          <p className="text-[10px] font-mono tracking-[0.35em] text-teal-400 uppercase mb-8">
            ReLoHu
          </p>
          <div className="w-12 h-12 rounded-full bg-teal-900/50 border border-teal-700 flex items-center justify-center mx-auto mb-8">
            <svg className="w-5 h-5 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
          </div>
          <h1 className="text-2xl font-light text-white mb-4">Your map is on its way.</h1>
          <p className="text-slate-400 leading-relaxed mb-2">
            Check your inbox at <span className="text-teal-400">{email}</span>.
          </p>
          <p className="text-slate-500 text-sm leading-relaxed mb-12">
            It may take a minute or two to arrive. Check your spam folder if you do not see it.
          </p>
          <a
            href="/founding-cohort"
            className="inline-block bg-teal-600 hover:bg-teal-500 text-white px-8 py-3 rounded-full font-medium transition-colors text-sm"
          >
            See the full Terrain Map offer
          </a>
          <Link
            href="/"
            className="mt-6 block text-slate-600 hover:text-slate-400 text-sm transition-colors"
          >
            Back to ReLoHu
          </Link>
        </div>
      </div>
    )
  }

  return null
}
